"""empty message

Revision ID: 6466abf882a7
Revises: 208c3e577035
Create Date: 2024-04-25 21:04:26.188313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6466abf882a7'
down_revision = '208c3e577035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['picture'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('picture',
               existing_type=sa.String(length=250),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('picture',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
